# See https://docs.redoc.ly/cli/configuration/ for more information.
apis:
  core:
    root: "openapi/openapi.yaml"
lint:
  plugins:
    - './plugins/local.js'
  extends:
    - recommended
  rules:
    tag-description: off
  preprocessors:
    local/merge-schemas: on
features.openapi:
  showConsole: true
  layout:
    scope: section
  routingStrategy: browser
  htmlTemplate: ./web/index.html
